osx_image: beta-xcode6.2
language: objective-c

env:
  global:
    secure: "nNOR1HgbuY1Z1SgsHyn2p2EtcC7N8HMJvv3BrQwnY7Fzg6dkIFWISAZYzzijXaqN0BJ+lvKHSO8F4HjWRL64x868bPSMdf3xlqG2VR5yvKsFfpjwqxoyDsBYc68VPsH+tcZqQt4SC2wAqGSkOOF3Pn/4yGyoCGZWWq05cN05las="

cache:
  - bundler
  - cocoapods

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - echo "machine github.com login $GITHUB_API_KEY" > ~/.netrc
  - chmod 600 ~/.netrc

before_script:
  - make ci
  
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - make oss
  - bundle exec pod install

script:
  - make test
  - make lint

notifications:
  slack:
    secure: "fXmNnx6XW5OvT/j2jSSHYd3mHwbL+GzUSUSWmZVT0Vx/Ga5jXINTOYRY/9PYgJMqdL8a/L0Mf/18ZZ+tliPlWQ/DnfTz1a3Q/Pf94hfYSGhSGlQC/eXYcpOm/dNOKYQ3sr4tqXtTPylPUDXHeiM2D59ggdlUvVwcALGgHizajPQ="
